### ISSUE TITLE
Create login page

### ISSUE THREAD

**Issue by taingra** [Good-nough-Software/meetup-app#1]

**Comment by lpbuccil** [comment]
Created Login page Login.scala.html with the controller LoginController. I also set the default route "/" to redirect to the login page.

**Comment by taingra** [comment]
Something I noticed while working on my page is @main() {} in the view automatically generates the <html>, <head>, <body> and puts the code in @main() { } inside them. So there are some redundancies in the login page. I'd remove them for you but I don't want to create git merge conflicts with your work. 

Take a look at the html that is generated in your browser and you'll see the redundant tags

**Comment by lpbuccil** [comment]
Created login page with username and password validation.
