### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by taingra** [Good-nough-Software/meetup-app#2]
We need at least a table for the users

**Comment by taingra** [comment]
## User table
 | id | username | passwordHash | usertype                | email  | name | phone | home location |
 |----|----------|--------------|-------------------------|--------|------|-------|---------------|
 |    | string   | string       | enum("admin", "user"... | string |      |       |  FK location  |

## Locations table
 | id | country | state | city | street address |
 |----|---------|-------|------|----------------|
 |    |         |       |      |                |


## User locations table
 | userid | why                           | location      | start | end |
 |--------|-------------------------------|---------------|-------|-----|
 | FK     | ENUM("enrolled", "worked at") | FK locations? |       |     |

**Comment by jmarek117** [comment]
Primary key for Users table : username, email
Primary key for Locations table : ID
Primary key for User Locations : userid (FK to User:ID), why, locationID (FK to Location:ID), start

**Comment by taingra** [comment]
I haven't tested this yet but I've added a sql script to create the database
```
-- Setup empty database for Meetup App

CREATE DATABASE IF NOT EXISTS meetup;

USE meetup;

CREATE TABLE users (
       id       UNSIGNED INT,
       username VARCHAR(32),
       password CHAR(40), -- fixed size of hash size
       usertype ENUM('admin', 'user', 'organizer'),
       email    VARCHAR(32),
       name     VARCHAR(32),
       phone    CHAR(11),
       location UNSIGNED INT,
       FOREIGN KEY (location) REFERENCES location (id),
       PRIMARY KEY (id, username, email)
);

CREATE TABLE locations (
       id      UNSIGNED INT PRIMARY KEY,
       country VARCHAR(20),
       state   VARCHAR(2),
       city    VARCHAR(32),
       zip     VARCHAR(9),
       address VARCHAR(64),
);

CREATE TABLE relations (
       id         UNSIGNED INT PRIMARY KEY,
       userid     UNSIGNED INT,
       locationid UNSIGNED INT,
       FOREIGN KEY (userid) REFERENCES users (id),
       FOREIGN KEY (locationid) REFERENCES locations (id)
);
```
