### ISSUE TITLE
Procedures for Database

### ISSUE THREAD

**Issue by taingra** [Good-nough-Software/meetup-app#33]
- UserAdd 
- UserValidate 
- UserPasswordChange

**Comment by jmarek117** [comment]
Interface
UserAdd(username, email, password)
UserValidate(username, password)
UserPasswordChange(username, oldPassword, newPassword)

**Comment by mbdomaga** [comment]
Could you add:
UpdateUser(username, password, name, email, phone)

**Comment by lpbuccil** [comment]
Could you also add a UserResetPassword(email, newPassword)

I need it for the email reset aspect.

**Comment by lpbuccil** [comment]
[debug] application - Unknown column 'user.password' in 'where clause'

When I execute this call.
CALL UserPasswordChange('lpbuccil','5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8','40d52f979e874c7717fafd9b8011d2098b1d11fa')

**Comment by lpbuccil** [comment]
Issue has been resolved
