### ISSUE TITLE
New authentication method?

### ISSUE THREAD

**Issue by taingra** [Good-nough-Software/meetup-app#37]
@lpbuccil Hey when you get a chance can you let me know what the new authentication method is for within other controllers @mbdomaga code in UserProfileController.java and UserAccountSettingsController.java use the following method:
```
if (LoginController.validateUser(username, password) != 1) {
// do authenticated thing
```
which no longer works in the latest iteration of your LoginController. I understand from what you said in class and from your code it now has to do with [sessions](https://www.playframework.com/documentation/2.6.x/JavaSessionFlash)? So would it be something like 
```
if (session("username") != null) {
```

**Comment by lpbuccil** [comment]
Yeah, if you look in login controller, there is a part that assigns the
session username based off of if the user is found in the database. If the
user is not found then it will assign it as null.
