### ISSUE TITLE
Issue connecting to database

### ISSUE THREAD

**Issue by lpbuccil** [Good-nough-Software/meetup-app#44]
![screen shot 2018-11-18 at 3 22 18 pm](https://user-images.githubusercontent.com/32315918/48677641-e01bf700-eb45-11e8-8def-6e03aa34182f.png)

LucassMacBookAir:~ lucasbuccilli$ mysql -u meet -D meetup -h 47.6.36.43 -P 3306 -p
Enter password: 
ERROR 2002 (HY000): Can't connect to MySQL server on '47.6.36.43' (36)

**Comment by taingra** [comment]
Sorry, I unplugged everything when I went downstate without thinking. I am working on bringing the database back online

**Comment by taingra** [comment]
Okay I think it should be working, I cannot test it can be connected to remotely. Please let me know if you can connect

**Comment by taingra** [comment]
The address has changed I will send out an email with the information

**Comment by lpbuccil** [comment]
![screen shot 2018-11-26 at 2 11 19 pm](https://user-images.githubusercontent.com/32315918/49036326-660ef200-f185-11e8-9671-ddf7c2635203.png)
Im getting this issue now

**Comment by lpbuccil** [comment]
Issue is resolved
